services:
  - type: web
    name: strategic-console
    env: python
    buildCommand: "pip install ."
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    plan: free
